### ISSUE TITLE
Click on "retired" does not work

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#321] opened 2016-02-08 13:57 UTC
The diorite package is retired [1]. Pointing at "retired" text, it says I should click for more info. Nevertheless, after click, the ```No `dead.package` file found``` message is displayed while there seems to be the dead.package file in the repo [2].

(Was this adjusted to the namespaced URL?)

[1] https://admin.fedoraproject.org/pkgdb/package/rpms/diorite/
[2] http://pkgs.fedoraproject.org/cgit/rpms/diorite.git/tree/dead.package

**Comment by pypingou** [comment] 2016-02-08 14:01
This is a duplicate of https://github.com/fedora-infra/pkgdb2/issues/319

**Closed** 2016-02-08 14:02 UTC
